### ISSUE TITLE
请问大佬识别眼睛的算法是哪部分啊

### ISSUE THREAD

**Issue by AL-Mazai** [rossning92/head-tracked-3d#5]

**Comment by AL-Mazai** [comment]
是这个吗 head-tracker.ts

**Comment by GGBoy5017** [comment]
你是不是发错地方了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rossning92/head-tracked-3d"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月15日(星期天) 晚上10:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[rossning92/head-tracked-3d] 请问大佬识别眼睛的算法是哪部分啊 (Issue #5)

**Comment by AL-Mazai** [comment]
> 你是不是发错地方了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rossning92/head-tracked-3d" ***@***.***&gt;; 发送时间:&nbsp;2022年5月15日(星期天) 晚上10:27 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[rossning92/head-tracked-3d] 请问大佬识别眼睛的算法是哪部分啊 (Issue #5) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

啊？

**Comment by rossning92** [comment]
@Zzw-mazai https://github.com/rossning92/head-tracked-3d/blob/master/src/head-tracker.ts#L100
